### ISSUE TITLE
support for Golang sdk

### ISSUE THREAD

**Issue by zach030** [zilliztech/cloud-vectordb-examples#2]
I try to use Golang sdk to make the connection but failed.
Any guide for Golang sdk or API about zilliz cloud service?

**Comment by shanghaikid** [comment]
I think you can try milvus golang sdk directly. but it is not officially supported.  some of the api are not supported, such as partition or rbac related features. but most of the api should work.  https://github.com/milvus-io/milvus-sdk-go

> I try to use Golang sdk to make the connection but failed. Any guide for Golang sdk or API about zilliz cloud service?
